### ISSUE TITLE
Change Description on Signatures Folder

### ISSUE THREAD

**Issue by dcarlson-rvbd** [riverbed/Riverbed-Community-Toolkit#1]
The description on the main Signatures folder should be something other than "O365 in French" as that won't be the only app in there.

**Comment by gwenblum** [comment]
It is not really a description of the folder but of the last "commit", and it will change each time code is modified under this folder (for example added).

If you have any kind of Aternit signature to share you can try to do a pull-request and set the commit description, or just send the signature to me and I will take care of it.
